# Generated by Django 6.1.1 on 2026-09-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop', models.CharField(choices=[('MUSIC', 'Music Loop'), ('IB', 'IB Loop')], max_length=10)),
                ('slot_number', models.PositiveIntegerField(help_text='Slot position, e.g 1 to 15')),
                ('bus_number', models.PositiveIntegerField(blank=True, help_text='Current bus number assigned to this slot.', max_length=4, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['loop', 'slot_number'],
                'unique_together': {('loop', 'slot_number')},
            },
        ),
    ]
