# Generated by Django 6.1.1 on 2026-09-20 22:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinLengthValidator(1000), django.core.validators.MaxLengthValidator(9999)])),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='BusStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_late', models.BooleanField(default=False)),
                ('arrived_time', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='AM.bus')),
            ],
            options={
                'ordering': ['date', 'bus__number'],
                'constraints': [models.UniqueConstraint(fields=('bus', 'date'), name='Unique_bus_per_day')],
            },
        ),
    ]
