# Generated by Django 6.1.1 on 2026-09-20 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AM', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['number'], 'verbose_name_plural': 'buses'},
        ),
        migrations.AlterModelOptions(
            name='busstatus',
            options={'ordering': ['date', 'bus__number'], 'verbose_name_plural': 'bus statuses'},
        ),
    ]
