# Generated by Django 6.1.1 on 2026-09-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busslot',
            name='bus_number',
            field=models.PositiveIntegerField(blank=True, help_text='Current bus number assigned to this slot.', null=True),
        ),
    ]
