# Generated by Django 6.1.1 on 2026-09-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loops', '0002_alter_busslot_bus_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busslot',
            options={'ordering': ['loop', 'slot_number'], 'verbose_name': 'bus_slot_tracking', 'verbose_name_plural': 'Bus Slot Tracking Database'},
        ),
        migrations.AlterModelTable(
            name='busslot',
            table='Bus_slot_tracking',
        ),
    ]
